// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

import 'book.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'books.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'books.g.dart';

@freezed
class Books with _$Books {
  const factory Books({
    @Default([]) List<Book> values,
  }) = _Books;

  factory Books.fromJson(Map<String, Object?> json)
      => _$BooksFromJson(json);
}