import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
import 'package:flutter_library_app/feature/books/books.dart';

part 'checkouts.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'checkouts.g.dart';

@freezed
class CheckoutsState with _$CheckoutsState {
  const factory CheckoutsState.loading() = _CheckoutsStateLoading;
  const factory CheckoutsState.data(Checkouts checkouts) = _CheckoutsStateData;
  const factory CheckoutsState.error({String? message}) = _CheckoutsStateError;

  factory CheckoutsState.fromJson(Map<String, Object?> json) =>
      _$CheckoutsStateFromJson(json);
}
