// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'book.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'book.g.dart';

@freezed
class Book with _$Book {
  const factory Book({
    required String id,
    required String title,
    required String author,
    required String isbn,
    required String publisher,
    @Default(null) String? description,
    @Default(null) String? available,
  }) = _Book;

  factory Book.fromJson(Map<String, Object?> json)
      => _$BookFromJson(json);
}