// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

import 'checkout.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'checkouts.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'checkouts.g.dart';

@freezed
class Checkouts with _$Checkouts {
  const factory Checkouts({
    @Default([]) List<Checkout> values,
  }) = _Checkouts;

  factory Checkouts.fromJson(Map<String, Object?> json)
      => _$CheckoutsFromJson(json);
}