// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'checkout.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'checkout.g.dart';

@freezed
class Checkout with _$Checkout {
  const factory Checkout({
    required String id,
    required String book,
    required String user,
    @Default(null) DateTime? returnDate,
    required DateTime dueDate,
    required DateTime date,

  }) = _Checkout;

  factory Checkout.fromJson(Map<String, Object?> json)
      => _$CheckoutFromJson(json);
}